---
collections:
  - ansible.posix
  - community.docker
  - community.general

roles:
  - name: aleksanderbl29.sonos_stream
    version: v0.2.1
  - name: aleksanderbl29.hyperhdr
    version: v1.0.0
  - name: ironicbadger.figurine
    version: 1.0.3
