---
- name: Homelab
  hosts: prod
  become: true
  vars_files:
    - /vars/docker-vars.yml
    - secrets/github_actions_secret.yml

  pre_tasks:
    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: "yes"
      when:
        - ansible_facts.os_family == "Debian"

  tasks:
    - name: Setup Docker
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Clone Git Repos
      ansible.builtin.import_tasks: tasks/git-repo.yml

    - name: Ensure Home Assistant is ready for deployment
      ansible.builtin.import_tasks: tasks/home-assistant.yml
      when: "'ha' is in ansible_hostname"

    - name: Deploy Docker Containers
      ansible.builtin.import_tasks: tasks/docker-deploy.yml

    - name: Setup CD
      ansible.builtin.import_tasks: tasks/cd.yml
      when: "'rpi4-1' is in ansible_hostname"
