---
- name: Homelab
  hosts: utm
  become: true
  vars_files:
    - /vars/docker-vars.yml

  pre_tasks:
    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: "yes"
      when:
        - ansible_facts.os_family == "Debian"

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Clone Git Repos
      ansible.builtin.import_tasks: tasks/git-repo.yml

    - name: Deploy Docker Containers
      ansible.builtin.import_tasks: tasks/docker-deploy.yml
