---
- name: Homelab
  hosts: dev
  become: true
  vars_files:
    - /vars/docker-vars.yml

  pre_tasks:
    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Check containers are running
      ansible.builtin.import_tasks: handlers/docker-handler.yml

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Clone Git Repos
      ansible.builtin.import_tasks: tasks/git-repo.yml

    - name: Deploy Docker Containers
      ansible.builtin.import_tasks: tasks/docker-deploy.yml
