---
- name: Homelab
  hosts: prod
  become: true
  vars_files:
    - /vars/docker-vars.yml
    - ./secrets/slack_code.yml

  pre_tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: "yes"
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure Nala is installed on performant devices
      ansible.builtin.apt:
        name: nala
        state: present
      when:
        - ansible_memtotal_mb > 2000
        - ansible_facts.os_family == "Debian"

    - name: Ensure wifi is disabled on pihole devices
      ansible.builtin.cron:
        name: "Disable wifi"
        special_time: reboot
        job: ifconfig wlan0 down

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Clone Git Repos
      ansible.builtin.import_tasks: tasks/git-repo.yml

    - name: Ensure Home Assistant is ready for deployment
      ansible.builtin.import_tasks: tasks/home-assistant.yml
      when: "'ha' is in ansible_hostname"

    - name: Ensure needed files are in place for docker deployment
      ansible.builtin.import_tasks: tasks/docker-env.yml

    - name: Deploy Docker Containers
      ansible.builtin.import_tasks: tasks/docker-deploy.yml

    - name: Send Slack notification
      community.general.slack:
        token: "{{ slack_webhook }}"
        msg: "Ansible run complete at {{ ansible_date_time.iso8601 }}"
        channel: "#ansible"
        username: "Ansible"
