---
- name: Homelab
  hosts: prod
  become: true
  vars_files:
    - ./vars/docker-vars.yml
    - ./vars/hyperhdr-vars.yml
    - ./vars/hyperion-vars.yml
    - ./secrets/slack_code.yml

  pre_tasks:
    - name: PRE TASK | Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 10800
        upgrade: "yes"
      when:
        - ansible_facts.os_family == "Debian"

    - name: PRE TASK | Ensure Nala is installed on performant devices
      ansible.builtin.apt:
        name: nala
        state: present
      when:
        - ansible_memtotal_mb > 2000
        - ansible_facts.os_family == "Debian"

    # - name: PRE TASK | Ensure wifi is disabled on wired devices
    #   ansible.builtin.cron:
    #     name: "Disable wifi"
    #     special_time: reboot
    #     job: ifconfig wlan0 down
    #   when: "'hyperhdr' is not in ansible_hostname"

  handlers:
    - name: HANDLER | Restart services
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/homelab/{{ item }}/
        state: present
        recreate: always
      with_items:
        # - "pihole/pihole-docker"
        - "bind9"
        - "dashboard"
        - "portainer-traefik"

  tasks:
    - name: Setup Docker
      ansible.builtin.import_tasks: tasks/docker.yml
      when: "'hyperhdr' is not in ansible_hostname"

    - name: Clone Git Repos
      ansible.builtin.import_tasks: tasks/git-repo.yml
      when: "'hyperhdr' is not in ansible_hostname"

    - name: Prepare Home Assistant deployment
      ansible.builtin.import_tasks: tasks/home-assistant.yml
      when: "'ha' is in ansible_hostname"

    - name: Prepare Docker deployment
      ansible.builtin.import_tasks: tasks/docker-env.yml
      when: "'hyperhdr' is not in ansible_hostname"

    - name: Deploy Docker Containers
      ansible.builtin.import_tasks: tasks/docker-deploy.yml
      when: "'hyperhdr' is not in ansible_hostname"

    - name: Setup CD
      ansible.builtin.import_tasks: tasks/cd.yml
      when: "'rpi4-1' is in ansible_hostname"

    - name: Deploy hyperion
      ansible.builtin.import_tasks: tasks/hyperion.yml
      when: "'hyperhdr' is in ansible_hostname"

    # - name: Deploy hyperhdr
    #   ansible.builtin.import_tasks: tasks/hyperhdr.yml
    #   when: "'hyperhdr' is in ansible_hostname"

  post_tasks:
    - name: POST TASK | Get temperature of devices
      ansible.builtin.command:
        cmd: vcgencmd measure_temp
      changed_when: false
      register: temperature

    - name: POST TASK | Print temperature
      ansible.builtin.debug:
        msg: "{{ temperature.stdout }}"

    - name: POST TASK | Check voltage throttling
      ansible.builtin.command:
        cmd: vcgencmd get_throttled
      changed_when: false
      register: throttling

    - name: POST TASK | Print voltage throttling
      ansible.builtin.debug:
        msg: "{{ throttling.stdout }}"

    - name: POST TASK | Send Slack notification
      community.general.slack:
        token: "{{ slack_webhook }}"
        msg: "Run on {{ ansible_hostname }} complete and the device is at {{ temperature.stdout }}"
        channel: "#ansible"
        username: "Ansible"
