- name: Create directory "deployment"
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/deployment
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"

- name: Copy cd.inventory.ini
  ansible.builtin.copy:
    src: ../cd.inventory.ini
    dest: /home/{{ ansible_user }}/deployment/cd.inventory.ini
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"

- name: Copy env file to docker folder
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"
  loop:
    - { src: "../../homelab/semaphore/.env", dest: "/home/{{ ansible_user }}/homelab/semaphore/.env" }

- name: Generate encryption key for semaphore
  ansible.builtin.command:
    cmd: "head -c32 /dev/urandom | base64"
  register: semaphore_encryption_key

- name: Put encryption key in env file
  ansible.builtin.lineinfile:
    line: "SEMAPHORE_ACCESS_KEY_ENCRYPTION=${{ semaphore_encryption_key.stdout }}"
    search_string: "SEMAPHORE_ACCESS_KEY_ENCRYPTION="
    path: /home/{{ ansible_user }}/homelab/semaphore/.env

- name: Deploy ansible semaphore
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user }}/homelab/semaphore/
    state: present

# - name: Setup Github Actions runner
#   ansible.builtin.include_role:
#     name: macunha1.github_actions_runner
#   vars:
#     gh_runner_config_labels:
#       - ansible
#       - self-hosted
#       - linux
#       - "{{ ansible_distribution }}"
#       - "{{ ansible_distribution_release }}"
#       - "{{ ansible_hostname }}"
#       - "{{ ansible_architecture }}"
#     gh_runner_config_url: https://github.com/aleksanderbl29/homelab
#     gh_runner_config_token: "{{ secret_github_actions_runner_access_token }}"


# - name: Setup github actions runner
#   ansible.builtin.include_role:
#     name: monolithprojects.github_actions_runner
#   vars:
#     github_actions_runner_github_account: "aleksanderbl29"
#     github_actions_runner_github_repo: "aleksanderbl29/homelab"
#     github_actions_runner_runner_user: "{{ ansible_user }}"
#     github_actions_runner_runner_state: "started"
#     github_actions_runner_access_token: "{{ secret_github_actions_runner_access_token }}"
