- name: CD | Create directory "deployment"
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/deployment
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"

- name: CD | Clone git repo
  ansible.builtin.git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
  become: false
  with_items:
    - {repo: 'aleksanderbl29/ansible4homelab', dest: '/home/{{ ansible_user }}/ansible4homelab', version: 'main'}

- name: CD | Copy cd.inventory.ini
  ansible.builtin.copy:
    src: ../cd.inventory.ini
    dest: /home/{{ ansible_user }}/deployment/cd.inventory.ini
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"

- name: CD | Copy env file to docker folder
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"
  loop:
    - { src: "../../homelab/semaphore/.env", dest: "/home/{{ ansible_user }}/homelab/semaphore/.env" }

- name: CD | Add secrets folder
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/ansible4homelab/secrets/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"

- name: CD | Copy Ansible secrets to repository
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"
  loop:
    - { src: "./secrets/pihole_secrets.yml", dest: "/home/{{ ansible_user }}/ansible4homelab/secrets/pihole_secrets.yml" }
    - { src: "./secrets/secrets.yaml", dest: "/home/{{ ansible_user }}/ansible4homelab/secrets/secrets.yaml" }
    - { src: "./secrets/slack_code.yml", dest: "/home/{{ ansible_user }}/ansible4homelab/secrets/slack_code.yml" }

# - name: CD | Generate encryption key for semaphore
#   ansible.builtin.command:
#     cmd: "head -c32 /dev/urandom | base64"
#   register: semaphore_encryption_key

# - name: CD | Put encryption key in env file
#   ansible.builtin.lineinfile:
#     line: "SEMAPHORE_ACCESS_KEY_ENCRYPTION=${{ semaphore_encryption_key.stdout }}"
#     search_string: "SEMAPHORE_ACCESS_KEY_ENCRYPTION="
#     path: /home/{{ ansible_user }}/homelab/semaphore/.env

- name: CD | Deploy ansible semaphore
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user }}/homelab/semaphore/
    state: present
