---
- name: SETUP DOCKER | Check if Docker is already present.
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: SETUP DOCKER | Download Docker install convenience script.
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: "0775"
  when: docker_command_result.rc != 0

- name: SETUP DOCKER | Run Docker install convenience script.
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc != 0

- name: SETUP DOCKER | Ensure Docker is started.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: SETUP DOCKER | Ensure dependencies are installed (Debian).
  ansible.builtin.apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - git
      - rsync
    state: present
  when: ansible_facts.os_family == "Debian"

- name: SETUP DOCKER | Ensure dependencies are installed (Archlinux).
  community.general.pacman:
    name:
      - libffi
      - openssl
      - base-devel
      - python-pip
      - git
      - rsync
    state: present
  when: ansible_facts.os_family == "Archlinux"

- name: SETUP DOCKER | Install Docker Compose.
  ansible.builtin.apt:
    name: docker-compose
    state: present

- name: "SETUP DOCKER | Ensure user is added to the docker group: {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

# reset_connection doesn't support conditionals.
- name: SETUP DOCKER | Reset connection so docker group is picked up.
  ansible.builtin.meta: reset_connection

- name: SETUP DOCKER | Setup docker networks
  community.docker.docker_network:
    name: "{{ item }}"
  loop:
    - proxy
    - media
    - external
    - database

- name: SETUP DOCKER | Setup docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
  loop:
    - portainer_data
