---
- name: PREPARE DOCKER DEPLOYMENT | Copy env files
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0774"
  loop:
    - { src: "../../homelab/pihole/pihole-docker/.env", dest: "/home/{{ ansible_user }}/homelab/pihole/pihole-docker/.env" }
    - { src: "../../homelab/traefik/.env", dest: "/home/{{ ansible_user }}/homelab/traefik/.env" }
    - { src: "../../homelab/traefik/.env", dest: "/home/{{ ansible_user }}/homelab/portainer-traefik/.env" }
    - { src: "../../homelab/watchtower/.env", dest: "/home/{{ ansible_user }}/homelab/watchtower/.env" }
    - { src: "../../homelab/uptime-kuma/.env", dest: "/home/{{ ansible_user }}/homelab/uptime-kuma/.env" }
    - { src: "../../homelab/cloudflare-tunnel/.env", dest: "/home/{{ ansible_user }}/homelab/cloudflare-tunnel/.env" }
    - { src: "../../homelab/homepage/.env", dest: "/home/{{ ansible_user }}/homelab/homepage/.env" }
    - { src: "../../homelab/postgres/.env", dest: "/home/{{ ansible_user }}/homelab/postgres/.env" }
    - { src: "../../homelab/gatus/.env", dest: "/home/{{ ansible_user }}/homelab/gatus/.env" }
    - { src: "../../homelab/gitea/.env", dest: "/home/{{ ansible_user }}/homelab/gitea/.env" }
    # - { src: "../../homelab/stirling-pdf/.env", dest: "/home/{{ ansible_user }}/homelab/stirling-pdf/.env" }

- name: PREPARE DOCKER DEPLOYMENT | Create acme.json files
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/homelab/traefik/data/acme.json
    state: touch
    mode: "0600"
    access_time: preserve
    modification_time: preserve

- name: PREPARE DOCKER DEPLOYMENT | Disable systemd-resolved
  ansible.builtin.shell:
    cmd: "sudo sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf"
  when: ansible_os_family == "Debian"
  changed_when: false

- name: PREPARE DOCKER DEPLOYMENT | Disable systemd-resolved
  ansible.builtin.shell:
    cmd: "sudo sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'"
  when: ansible_os_family == "Debian"
  changed_when: false

- name: PREPARE DOCKER DEPLOYMENT | Disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  when: ansible_os_family == "Debian"
  changed_when: false
