---
- name: "Ensure Git is installed"
  ansible.builtin.apt:
    name: git
    state: present

- name: "Clone General Git Repositories"
  ansible.builtin.git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
  become: false
  with_items:
    - {repo: 'aleksanderbl29/homelab', dest: '/home/{{ ansible_user }}/homelab', version: 'main'}

- name: "Clone HomeAssistant Repository"
  ansible.builtin.git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
  when: "'ha' in ansible_hostname"
  become: false
  with_items:
    - {repo: 'aleksanderbl29/homeassistant-config', dest: '/home/{{ ansible_user }}/homeassistant/config', version: 'main'}
