- name: Copy secrets file to HA host
  ansible.builtin.copy:
    src: ../secrets/secrets.yml
    dest: /home/{{ ansible_user }}/homeassistant/config/secrets.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: "0774"
  when: "'ha' in ansible_hostname"
