---
- name: Check if curl is installed
  command: "type -p curl >/dev/null"
  register: curl_check
  ignore_errors: true

- name: Install curl if not installed
  apt:
    name: curl
    state: present
  when: curl_check.rc != 0

- name: Download HyperHDR public key
  shell: "curl -fsSL https://awawa-dev.github.io/hyperhdr.public.apt.gpg.key"
  register: hyperhdr_key

- name: Save HyperHDR public key
  copy:
    content: "{{ hyperhdr_key.stdout }}"
    dest: /usr/share/keyrings/hyperhdr.public.apt.gpg.key
    mode: '0644'

- name: Add HyperHDR repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hyperhdr.public.apt.gpg.key] https://awawa-dev.github.io {{ ansible_distribution_release }} main"
    state: present

- name: Update apt cache
  apt:
    update_cache: true

- name: Install HyperHDR
  apt:
    name: hyperhdr
    state: present
