---
- name: Verify hyperhdr service
  become: true
  ansible.builtin.service:
    name: hyperhdr@root.service
    state: started

- name: Validate connection to hyperhdr servers
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 8090
    timeout: 30
    active_connection_states: ESTABLISHED
