---
- name: Teardown of Homelab
  hosts: prod
  become: true

  tasks:
    # - name: Teardown hyperhdr
    #   ansible.builtin.import_tasks: teardown-tasks/hyperhdr.yml

    - name: Teardown docker containers
      ansible.builtin.import_tasks: teardown-tasks/docker-takedown.yml
