---
- name: Get device ID for soundcard
  ansible.builtin.shell:
    # cmd: $(arecord -l | awk '/^card/ {gsub(/:/,"",$2); print $2}')
    cmd: arecord -l | grep CODEC | awk '/^card/ {gsub(/:/,"",$2); print $2}'
  register: soundcard_id

- name: Write soundcard id to darkice configuration file
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/darkice/darkice.cfg
    line: "device          = plughw:{{ soundcard_id.stdout }},0 # Soundcard device for the audio input"
    regexp: "^device"
    state: present
    create: false
    owner: "{{ ansible_user }}"
    # mode: "0644"
    mode: "777"

- name: Write soundcard id to darkice configuration file in etc
  ansible.builtin.lineinfile:
    path: /etc/darkice.cfg
    line: "device          = plughw:{{ soundcard_id.stdout }},0 # Soundcard device for the audio input"
    regexp: "^device"
    state: present
    create: false
    owner: "{{ ansible_user }}"
    # mode: "0644"
    mode: "777"

- name: Write username to icecast configuration file
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/icecast2/icecast.xml
    line: "<user>{{ ansible_user }}</user>"
    regexp: "<user>"
    state: present
    create: false
    owner: "{{ ansible_user }}"
    # mode: "0644"
    mode: "777"

- name: Write group to icecast configuration file
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/icecast2/icecast.xml
    line: "<group>{{ ansible_user }}</group>"
    regexp: "<group>"
    state: present
    create: false
    owner: "{{ ansible_user }}"
    # mode: "0644"
    mode: "777"
