---
- name: Validate connection to server
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 8000
    timeout: 30
    active_connection_states: ESTABLISHED
  when: disable_conn_validation is false

- name: Check if stream is reachable
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:8000/rapi.mp3"
    method: GET
    return_content: false
  register: url_check
  when: disable_stream_endpoint_check is false

- name: Print URL status
  ansible.builtin.debug:
    msg: "Streaming service is {{ 'reachable' if url_check.status == 200 else 'unreachable' }}"
  when: disable_stream_endpoint_check is false
