---
name: "CI"
'on':
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * 1,3,5,6'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install yamllint ansible-lint ansible

      - name: yamllint
        run: yamllint .

      - name: ansible-lint
        run: ansible-lint .

      - name: ansible-playbook syntax check
        run: ansible-playbook main.yml -i localhost --syntax-check

  # molecule:
  #   name: Molecule
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro:
  #         - ubuntu2004
  #         - ubuntu2204
  #         - ubuntu2404
  #         - debian12
  #         - debian11
  #         - debian10

  #   steps:
  #     - name: Check out the codebase.
  #       uses: actions/checkout@v4

  #     - name: Set up Python 3.
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'

  #     - name: Install test dependencies.
  #       run: pip3 install ansible molecule molecule-plugins[docker] docker

  #     # - name: Install role dependencies.
  #     #   run: ansible-galaxy role install -r requirements.yml

  #     - name: Run Molecule tests.
  #       run: molecule test
  #       env:
  #         PY_COLORS: '1'
  #         ANSIBLE_FORCE_COLOR: '1'
  #         MOLECULE_DISTRO: ${{ matrix.distro }}
